include:
  - local: '/ci/.build.yaml'
  - local: '/ci/.tests.yaml'
  - local: '/ci/.deploy.yaml'

default:
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

stages:
  - build
  - test
  - deploy

build:
  tags:
    - docker
  stage: build
  extends: .build

test-backend:
  stage: test
  extends: .backend-tests

test-frontend:
  stage: test
  extends: .frontend-tests

deploy:
  stage: deploy
  tags:
    - docker
  extends: .deploy
