services:
  - docker:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose down --remove-orphans
    - docker-compose build

test-backend:
  image: maven:3.8.5-openjdk-17-alpine
  stage: test
  tags:
    - docker
  services:
    - name: mysql:5.7
  variables:
    MYSQL_DATABASE: hobbie_db
    MYSQL_ROOT_PASSWORD: root
  script:
    - cd springboot-backend
    - mvn test

test-frontend:
  image: node:18-alpine
  stage: test
  tags:
    - docker
  before_script:
    - cd react-frontend
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker-compose build

    - docker tag springboot-backend:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-springboot-backend:latest
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-springboot-backend:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-springboot-backend:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-springboot-backend:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-springboot-backend:${CI_COMMIT_SHORT_SHA}
  
    - docker tag react-frontend:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-react-frontend:latest
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-react-frontend:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-react-frontend:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-react-frontend:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-react-frontend:${CI_COMMIT_SHORT_SHA}

    - docker tag nginx:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-nginx:latest
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-nginx:latest
    - docker tag ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME]-nginx:latest ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-nginx:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_NAME}-nginx:${CI_COMMIT_SHORT_SHA}

