stages:
  - build

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose build
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag docker.io/library/frontend $CONTAINER_RELEASE_IMAGE/frontend
    - docker tag docker.io/library/backend $CONTAINER_RELEASE_IMAGE/backend
    - docker tag docker.io/library/nginx $CONTAINER_RELEASE_IMAGE/nginx
    - docker push $CONTAINER_RELEASE_IMAGE/frontend
    - docker push $CONTAINER_RELEASE_IMAGE/backend
    - docker push $CONTAINER_RELEASE_IMAGE/nginx
  only:
    changes:
      - react-frontend/*
      - spring-backend/*
