default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  rules:
    - when:
      changes:
        - react-frontend/*
        - spring-backend/*

stages:
  - build
  - publish

build:
  stage: build
  script:
    - docker-compose build
    - docker tag docker.io/library/lab-5-client $CI_REGISTRY_IMAGE/client
    - docker tag docker.io/library/lab-5-server $CI_REGISTRY_IMAGE/server
    - docker tag docker.io/library/lab-5-nginx $CI_REGISTRY_IMAGE/nginx

publish:
  stage: publish
  script:
    - docker push $CI_REGISTRY_IMAGE/client
    - docker push $CI_REGISTRY_IMAGE/server
    - docker push $CI_REGISTRY_IMAGE/nginx