.build:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose build
    - docker tag docker.io/library/lab-5-client $CI_REGISTRY_IMAGE/client
    - docker tag docker.io/library/lab-5-server $CI_REGISTRY_IMAGE/server
    - docker tag docker.io/library/lab-5-nginx $CI_REGISTRY_IMAGE/nginx
    - docker push $CI_REGISTRY_IMAGE/client
    - docker push $CI_REGISTRY_IMAGE/server
    - docker push $CI_REGISTRY_IMAGE/nginx