name: CI-CD Pipeline

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Run tests
        run: mvn test
        working-directory: spring-backend

  deploy:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      image_tag: ${{ steps.docker_meta.outputs.tags }}
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKER_USERNAME  }}/spring-backend
        tags: |
          type=sha,format=long
          type=ref,event=branch
          latest
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_TOKEN  }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: ./spring-backend
        file: ./spring-backend/Dockerfile
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}